services:
  backend:
    build:
      context: ./app-backend
    container_name: land-revenue-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./angular-frontend
    container_name: land-revenue-angular-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
